version: 2

project_name: gopack

before:
  hooks:
    - go mod tidy

builds:
  - id: gopack
    main: .
    binary: gopack
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/Go-Python-Toolchain/gopack/cmd.version={{ .Version }}
      - -X github.com/Go-Python-Toolchain/gopack/cmd.commit={{ .Commit }}
      - -X github.com/Go-Python-Toolchain/gopack/cmd.date={{ .Date }}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: Go-Python-Toolchain
    name: gopack
